### ISSUE TITLE
Installation complaining about  libsodium.so.23 for version 2.2.0 with solution

### ISSUE THREAD

**Issue by BjornFJohansson** [Anaconda-Platform/nb_conda_kernels#117]
Hi, I had the problems below trying to upgrade to 2.2.0.
There were complains about " libsodium.so.23" which seem to be connected to "zmq".
I do not know if this is the right place, but I put it here for reference.

solved by `conda install -c conda-forge libsodium`

```
(base) bjorn@thinkp:~$ conda update nb_conda_kernels
Solving environment: | done

## Package Plan ##

  environment location: /home/bjorn/anaconda3

  added / updated specs: 
    - nb_conda_kernels


The following packages will be UPDATED:

    nb_conda_kernels: 2.1.0-py36_0 conda-forge --> 2.2.0-py36_1000 conda-forge

Preparing transaction: done
Verifying transaction: done
Executing transaction: / + /home/bjorn/anaconda3/bin/python -m nb_conda_kernels.install --disable --prefix=/home/bjorn/anaconda3
Traceback (most recent call last):
  File "/home/bjorn/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/bjorn/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/nb_conda_kernels/__init__.py", line 3, in <module>
    from .manager import CondaKernelSpecManager
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/nb_conda_kernels/manager.py", line 11, in <module>
    from jupyter_client.kernelspec import (
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/jupyter_client/connect.py", line 23, in <module>
    import zmq
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libsodium.so.23: cannot open shared object file: No such file or directory

WARNING conda.core.link:run_script(813): pre-unlink script failed for package conda-forge::nb_conda_kernels-2.1.0-py36_0
consider notifying the package maintainer
\ + /home/bjorn/anaconda3/bin/python -m nb_conda_kernels.install --enable
Traceback (most recent call last):
  File "/home/bjorn/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/bjorn/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/nb_conda_kernels/__init__.py", line 2, in <module>
    from .manager import CondaKernelSpecManager
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/nb_conda_kernels/manager.py", line 13, in <module>
    from jupyter_client.kernelspec import KernelSpecManager, KernelSpec, NoSuchKernel
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/jupyter_client/connect.py", line 23, in <module>
    import zmq
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libsodium.so.23: cannot open shared object file: No such file or directory

failed
ERROR conda.core.link:_execute(502): An error occurred while installing package 'conda-forge::nb_conda_kernels-2.2.0-py36_1000'.
LinkError: post-link script failed for package conda-forge::nb_conda_kernels-2.2.0-py36_1000
running your command again with `-v` will provide additional information
location of failed script: /home/bjorn/anaconda3/bin/.nb_conda_kernels-post-link.sh
==> script messages <==
+ /home/bjorn/anaconda3/bin/python -m nb_conda_kernels.install --enable
Traceback (most recent call last):
  File "/home/bjorn/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/bjorn/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/nb_conda_kernels/__init__.py", line 2, in <module>
    from .manager import CondaKernelSpecManager
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/nb_conda_kernels/manager.py", line 13, in <module>
    from jupyter_client.kernelspec import KernelSpecManager, KernelSpec, NoSuchKernel
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/jupyter_client/connect.py", line 23, in <module>
    import zmq
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libsodium.so.23: cannot open shared object file: No such file or directory


Attempting to roll back.

Rolling back transaction: done

LinkError: post-link script failed for package conda-forge::nb_conda_kernels-2.2.0-py36_1000
running your command again with `-v` will provide additional information
location of failed script: /home/bjorn/anaconda3/bin/.nb_conda_kernels-post-link.sh
==> script messages <==
+ /home/bjorn/anaconda3/bin/python -m nb_conda_kernels.install --enable
Traceback (most recent call last):
  File "/home/bjorn/anaconda3/lib/python3.6/runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "/home/bjorn/anaconda3/lib/python3.6/runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/nb_conda_kernels/__init__.py", line 2, in <module>
    from .manager import CondaKernelSpecManager
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/nb_conda_kernels/manager.py", line 13, in <module>
    from jupyter_client.kernelspec import KernelSpecManager, KernelSpec, NoSuchKernel
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/jupyter_client/__init__.py", line 4, in <module>
    from .connect import *
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/jupyter_client/connect.py", line 23, in <module>
    import zmq
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/__init__.py", line 47, in <module>
    from zmq import backend
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/utils/sixcerpt.py", line 34, in reraise
    raise value
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/backend/__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/backend/select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "/home/bjorn/anaconda3/lib/python3.6/site-packages/zmq/backend/cython/__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: libsodium.so.23: cannot open shared object file: No such file or directory




(base) bjorn@thinkp:~$ conda install -c conda-forge libsodium
Solving environment: done

## Package Plan ##

  environment location: /home/bjorn/anaconda3

  added / updated specs: 
    - libsodium


The following packages will be UPDATED:

    libsodium: 1.0.13-h31c71d8_2 defaults --> 1.0.16-h470a237_1 conda-forge

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
(base) bjorn@thinkp:~$ conda update nb_conda_kernels
Solving environment: done

## Package Plan ##

  environment location: /home/bjorn/anaconda3

  added / updated specs: 
    - nb_conda_kernels


The following packages will be UPDATED:

    nb_conda_kernels: 2.1.0-py36_0 conda-forge --> 2.2.0-py36_1000 conda-forge

Preparing transaction: done
Verifying transaction: done
Executing transaction: \ + /home/bjorn/anaconda3/bin/python -m nb_conda_kernels.install --disable --prefix=/home/bjorn/anaconda3
Disabling nb_conda_kernels...
Disabled nb_conda_kernels

- + /home/bjorn/anaconda3/bin/python -m nb_conda_kernels.install --enable
Enabling nb_conda_kernels...
Status: enabled

done
(base) bjorn@thinkp:~$ 
```

**Comment by mcg1969** [comment]
I don't believe this is the correct place—`nb_conda_kernels` depends on `libsodium` indirectly at best, through this chain of dependencies:
```
nb_conda_kernels -> jupyter_client -> zmq -> libsodium
```
This suggests a missing dependency for the `zmq` library. I really don't think there's anything we should do within `nb_conda_kernels` to fix this; [this](https://github.com/conda-forge/zeromq-feedstock/issues/40) seems relevant.
