### ISSUE TITLE
pre-unlink script failed + nb_conda_kernels breaks anaconda guideline abould post-link scripts hence inability to create an env

### ISSUE THREAD

**Issue by kiwi0fruit** [Anaconda-Platform/nb_conda_kernels#120]
It calls some python code but it should only:

> Post-link and pre-unlink scripts should:
>
> * Be avoided whenever possible.
> * Not touch anything other than the files being installed.
> * Not write anything to stdout or stderr, unless an error occurs.
> * Not depend on any installed or to be installed conda packages.
> * Depend only on simple system tools such as rm, cp, mv and ln.

**Comment by kiwi0fruit** [comment]
This leads to inability to create environment with `nb_conda_kernels` with
> ImportError: DLL load failed:
as post-link script needs the environment to be activated to work.

**Comment by kiwi0fruit** [comment]
```
LinkError: post-link script failed for package defaults::nb_conda_kernels-2.2.0-py37_0
running your command again with `-v` will provide additional information
location of failed script: D:\User\Python\Miniconda3_x64\envs\python3\Scripts\.nb_conda_kernels-post-link.bat
==> script messages <==
Traceback (most recent call last):
  File "D:\User\Python\Miniconda3_x64\envs\python3\lib\runpy.py", line 183, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\User\Python\Miniconda3_x64\envs\python3\lib\runpy.py", line 109, in _get_module_details
    __import__(pkg_name)
  File "D:\User\Python\Miniconda3_x64\envs\python3\lib\site-packages\nb_conda_kernels\__init__.py", line 2, in <module>
    from .manager import CondaKernelSpecManager
  File "D:\User\Python\Miniconda3_x64\envs\python3\lib\site-packages\nb_conda_kernels\manager.py", line 13, in <module>
    from jupyter_client.kernelspec import KernelSpecManager, KernelSpec, NoSuchKernel
  File "D:\User\Python\Miniconda3_x64\envs\python3\lib\site-packages\jupyter_client\__init__.py", line 4, in <module>
    from .connect import *
  File "D:\User\Python\Miniconda3_x64\envs\python3\lib\site-packages\jupyter_client\connect.py", line 23, in <module>
    import zmq
  File "D:\User\Python\Miniconda3_x64\envs\python3\lib\site-packages\zmq\__init__.py", line 47, in <module>
    from zmq import backend
  File "D:\User\Python\Miniconda3_x64\envs\python3\lib\site-packages\zmq\backend\__init__.py", line 40, in <module>
    reraise(*exc_info)
  File "D:\User\Python\Miniconda3_x64\envs\python3\lib\site-packages\zmq\utils\sixcerpt.py", line 34, in reraise
    raise value
  File "D:\User\Python\Miniconda3_x64\envs\python3\lib\site-packages\zmq\backend\__init__.py", line 27, in <module>
    _ns = select_backend(first)
  File "D:\User\Python\Miniconda3_x64\envs\python3\lib\site-packages\zmq\backend\select.py", line 27, in select_backend
    mod = __import__(name, fromlist=public_api)
  File "D:\User\Python\Miniconda3_x64\envs\python3\lib\site-packages\zmq\backend\cython\__init__.py", line 6, in <module>
    from . import (constants, error, message, context,
ImportError: DLL load failed: ▒▒ ▒▒▒▒▒▒ ▒▒▒▒▒▒▒▒▒ ▒▒▒▒▒▒.

```

**Comment by kiwi0fruit** [comment]
Yet another problem that arises from this:

```
conda remove -n myenv --all
```
from withing base env gives:
```
/ Traceback (most recent call last):
  File "D:\Programs\Python\Miniconda3\envs\research\lib\runpy.py", line 183, in
_run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\Programs\Python\Miniconda3\envs\research\lib\runpy.py", line 109, in
_get_module_details
    __import__(pkg_name)
  File "D:\Programs\Python\Miniconda3\envs\research\lib\site-packages\nb_conda_k
ernels\__init__.py", line 2, in <module>
    from .manager import CondaKernelSpecManager
  File "D:\Programs\Python\Miniconda3\envs\research\lib\site-packages\nb_conda_k
ernels\manager.py", line 11, in <module>
    from traitlets import Unicode, Bool
  File "D:\Programs\Python\Miniconda3\envs\research\lib\site-packages\traitlets\
__init__.py", line 1, in <module>
    from .traitlets import *
  File "D:\Programs\Python\Miniconda3\envs\research\lib\site-packages\traitlets\
traitlets.py", line 60, in <module>
    from .utils.importstring import import_item
  File "D:\Programs\Python\Miniconda3\envs\research\lib\site-packages\traitlets\
utils\importstring.py", line 8, in <module>
    from ipython_genutils.py3compat import cast_bytes_py2
ModuleNotFoundError: No module named 'ipython_genutils.py3compat'

WARNING conda.core.link:run_script(1034): pre-unlink script failed for package d
efaults::nb_conda_kernels-2.2.0-py37_0
consider notifying the package maintainer
```
(Windows 7 x64 SP1)

**Comment by mcg1969** [comment]
I'm afraid there's little or nothing we can do about this. If we want `nb_conda_kernels` to work immediately after it is installed, it must use a post-link script in the manner we've implemented. In fact, a core member of the conda team has themselves contributed to the design of the post-link and pre-unlink scripts; and the `ipykernel` package requires a similar `post-link` script.

I would also suggest updating to 2.2.1 as soon as it is tagged. It is fixing a known issue with Windows activation.

**Comment by mcg1969** [comment]
I'm closing because, again, we're not going to be removing the post-link script; it is essential for correct installation and operation. I wish that were not the case but it is, due to the way Jupyter arranges its configuration files.
