### ISSUE TITLE
nb_conda_kernels does not find environments, when running jupyterlab as systemd service

### ISSUE THREAD

**Issue by tuxiano** [Anaconda-Platform/nb_conda_kernels#153]
Hi,

I'm setting up a jupyterlab server on ubuntu 18.04.3 and would like to start jupyterlab as systemd service.

**Issue:**
If I run jupyterlab as a systemd service, no conda environment is listed as a jupyter kernel.

If I run jupyterlab as jupyterlab user from the command line (`jupyter lab`), the conda environments are listed as a jupyter kernels.

**Expected behavior:**
If I run jupyterlab as a systemd service, conda environments should be listed as jupyter kernels.

**Systemd service (jupyter.service)**

```
[Unit]
Description=Jupyter Lab Server

[Service]
Type=simple
PIDFile=/run/jupyter.pid
ExecStart=/opt/miniconda3/bin/jupyter lab --config=/home/jupyterlab/.jupyter/jupyter_notebook_config.py
User=jupyterlab
Group=jupyterlab
WorkingDirectory=/opt/miniconda3
Restart=always
RestartSec=10
#KillMode=mixed

[Install]
WantedBy=multi-user.target
```

**base environment**

```
name: base
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - asn1crypto=1.2.0=py37_0
  - attrs=19.3.0=py_0
  - backcall=0.1.0=py_0
  - bleach=3.1.0=py_0
  - ca-certificates=2019.11.27=0
  - certifi=2019.11.28=py37_0
  - cffi=1.13.0=py37h2e261b9_0
  - chardet=3.0.4=py37_1003
  - conda=4.8.1=py37_0
  - conda-package-handling=1.6.0=py37h7b6447c_0
  - cryptography=2.8=py37h1ba5d50_0
  - decorator=4.4.1=py_0
  - defusedxml=0.6.0=py_0
  - entrypoints=0.3=py37_1000
  - idna=2.8=py37_0
  - importlib_metadata=1.4.0=py37_0
  - ipykernel=5.1.3=py37h5ca1d4c_0
  - ipython=7.11.1=py37h5ca1d4c_0
  - ipython_genutils=0.2.0=py_1
  - jedi=0.15.2=py37_0
  - jinja2=2.10.3=py_0
  - json5=0.8.5=py_0
  - jsonschema=3.2.0=py37_0
  - jupyter_client=5.3.4=py37_1
  - jupyter_core=4.6.1=py37_0
  - jupyterlab=1.2.5=py_0
  - jupyterlab_server=1.0.6=py_0
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.2.1=hd88cf55_4
  - libgcc-ng=9.1.0=hdf63c60_0
  - libsodium=1.0.17=h516909a_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - markupsafe=1.1.1=py37h516909a_0
  - mistune=0.8.4=py37h516909a_1000
  - more-itertools=8.1.0=py_0
  - nb_conda_kernels=2.2.2=py37_0
  - nbconvert=5.6.1=py37_0
  - nbformat=5.0.3=py_0
  - ncurses=6.1=he6710b0_1
  - nodejs=10.13.0=he6710b0_0
  - notebook=6.0.3=py37_0
  - openssl=1.1.1d=h7b6447c_3
  - pandoc=2.9.1.1=0
  - pandocfilters=1.4.2=py_1
  - parso=0.5.2=py_0
  - pexpect=4.7.0=py37_0
  - pickleshare=0.7.5=py37_1000
  - pip=19.3.1=py37_0
  - prometheus_client=0.7.1=py_0
  - prompt_toolkit=3.0.2=py_0
  - ptyprocess=0.6.0=py_1001
  - pycosat=0.6.3=py37h14c3975_0
  - pycparser=2.19=py37_0
  - pygments=2.5.2=py_0
  - pyopenssl=19.0.0=py37_0
  - pyrsistent=0.15.7=py37h516909a_0
  - pysocks=1.7.1=py37_0
  - python=3.7.4=h265db76_1
  - python-dateutil=2.8.1=py_0
  - pyzmq=18.1.1=py37h1768529_0
  - readline=7.0=h7b6447c_5
  - requests=2.22.0=py37_0
  - ruamel_yaml=0.15.46=py37h14c3975_0
  - send2trash=1.5.0=py_0
  - setuptools=41.4.0=py37_0
  - six=1.12.0=py37_0
  - sqlite=3.30.0=h7b6447c_0
  - terminado=0.8.3=py37_0
  - testpath=0.4.4=py_0
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.3=py37h516909a_0
  - tqdm=4.36.1=py_0
  - traitlets=4.3.3=py37_0
  - urllib3=1.24.2=py37_0
  - wcwidth=0.1.8=py_0
  - webencodings=0.5.1=py_1
  - wheel=0.33.6=py37_0
  - xz=5.2.4=h14c3975_4
  - yaml=0.1.7=had09818_2
  - zeromq=4.3.2=he1b5a44_2
  - zipp=2.0.0=py_1
  - zlib=1.2.11=h7b6447c_3
prefix: /opt/miniconda3

```
**.condarc**

```
envs_dirs:
  - /opt/miniconda3/envs/

```

Other information:

- Location of environments: `/opt/miniconda3/envs/`
- Location of jupyter config file `/home/jupyterlab/.jupyter/`

It would be great if you could help me with this.

Kind regards

**Comment by hadim** [comment]
I am running into a very similar and related issue using `jupyter_conda` that uses `nb_conda_kernels` under the hood.

The kernels are correctly listed but when starting a notebook with a conda kernel, here the error:

```
Jan 25 16:42:03 gollum bash[23077]: [I 16:42:03.790 LabApp] Kernel started: 017bc92f-49b6-48c7-be5c-d45cb0a856fb
Jan 25 16:42:03 gollum bash[23077]: Traceback (most recent call last):
Jan 25 16:42:03 gollum bash[23077]:   File "/home/hadim/local/conda/lib/python3.7/runpy.py", line 193, in _run_module_as_main
Jan 25 16:42:03 gollum bash[23077]:     "__main__", mod_spec)
Jan 25 16:42:03 gollum bash[23077]:   File "/home/hadim/local/conda/lib/python3.7/runpy.py", line 85, in _run_code
Jan 25 16:42:03 gollum bash[23077]:     exec(code, run_globals)
Jan 25 16:42:03 gollum bash[23077]:   File "/home/hadim/local/conda/lib/python3.7/site-packages/nb_conda_kernels/runner.py", line 32, in <module>
Jan 25 16:42:03 gollum bash[23077]:     exec_in_env(*(sys.argv[1:]))
Jan 25 16:42:03 gollum bash[23077]:   File "/home/hadim/local/conda/lib/python3.7/site-packages/nb_conda_kernels/runner.py", line 28, in exec_in_env
Jan 25 16:42:03 gollum bash[23077]:     os.execvp(ecomm[0], ecomm)
Jan 25 16:42:03 gollum bash[23077]:   File "/home/hadim/local/conda/lib/python3.7/os.py", line 572, in execvp
Jan 25 16:42:03 gollum bash[23077]:     _execvpe(file, args)
Jan 25 16:42:03 gollum bash[23077]:   File "/home/hadim/local/conda/lib/python3.7/os.py", line 614, in _execvpe
Jan 25 16:42:03 gollum bash[23077]:     raise last_exc
Jan 25 16:42:03 gollum bash[23077]:   File "/home/hadim/local/conda/lib/python3.7/os.py", line 605, in _execvpe
Jan 25 16:42:03 gollum bash[23077]:     exec_func(fullname, *argrest)
Jan 25 16:42:03 gollum bash[23077]: FileNotFoundError: [Errno 2] No such file or directory
```

and here is my systemd file:

```
[Unit]
Description=Jupyter
After=syslog.target network.target

[Service]
User=hadim
Group=hadim
ExecStart=/bin/bash -c "jupyter lab --no-browser --NotebookApp.token='' --ip=0.0.0.0"
Environment="PATH=/home/hadim/local/conda/bin/:$PATH"
WorkingDirectory=/home/hadim
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

ping @fcollonval and @mcg1969 in case one of you have an idea about it.

**Comment by hadim** [comment]
Looks like I found an easy fix by activating conda in systemd. New conf:

```
[Unit]
Description=Jupyter
After=syslog.target network.target

[Service]
User=hadim
Group=hadim
ExecStart=/bin/bash -c ". /home/hadim/local/conda/bin/activate && exec jupyter lab --no-browser --NotebookApp.token='' --ip=0.0.0.0"
Environment="PATH=/home/hadim/local/conda/bin/:$PATH"
WorkingDirectory=/home/hadim
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

@tuxiano give it a try and report here, please.

**Comment by tuxiano** [comment]
@hadim Sorry, for some reason I missed your feedback. I found an alternative solution:

```
[Unit]
Description=Jupyter Lab Server
After=syslog.target network.target

[Service]
User=jupyterlab
Environment="PATH=/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/opt/miniconda3/bin"
ExecStart=/opt/miniconda3/bin/jupyter lab
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
```

Thank you for your support.
