### ISSUE TITLE
Kernel Error: ModuleNotFoundError: No module named 'ntsecuritycon'

### ISSUE THREAD

**Issue by ShreeniketJoshi** [Anaconda-Platform/nb_conda_kernels#159]
Hi, I tried to install tensorflow environment. While I was successful doing that, and upon running the Jupyter notebook command through the command prompt, I'm getting a kernel error.

Previously the error mentioned win32 API was missing, I reinstalled all the files. And now I am getting this kernel error:

Traceback (most recent call last):
  File "E:\Software\Anaconda\lib\site-packages\tornado\web.py", line 1703, in _execute
    result = await result
  File "E:\Software\Anaconda\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "E:\Software\Anaconda\lib\site-packages\notebook\services\sessions\handlers.py", line 72, in post
    type=mtype))
  File "E:\Software\Anaconda\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "E:\Software\Anaconda\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "E:\Software\Anaconda\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 88, in create_session
    kernel_id = yield self.start_kernel_for_session(session_id, path, name, type, kernel_name)
  File "E:\Software\Anaconda\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "E:\Software\Anaconda\lib\site-packages\tornado\gen.py", line 742, in run
    yielded = self.gen.throw(*exc_info)  # type: ignore
  File "E:\Software\Anaconda\lib\site-packages\notebook\services\sessions\sessionmanager.py", line 101, in start_kernel_for_session
    self.kernel_manager.start_kernel(path=kernel_path, kernel_name=kernel_name)
  File "E:\Software\Anaconda\lib\site-packages\tornado\gen.py", line 735, in run
    value = future.result()
  File "E:\Software\Anaconda\lib\site-packages\tornado\gen.py", line 209, in wrapper
    yielded = next(result)
  File "E:\Software\Anaconda\lib\site-packages\notebook\services\kernels\kernelmanager.py", line 168, in start_kernel
    super(MappingKernelManager, self).start_kernel(**kwargs)
  File "E:\Software\Anaconda\lib\site-packages\jupyter_client\multikernelmanager.py", line 158, in start_kernel
    km.start_kernel(**kwargs)
  File "E:\Software\Anaconda\lib\site-packages\jupyter_client\manager.py", line 301, in start_kernel
    kernel_cmd, kw = self.pre_start_kernel(**kw)
  File "E:\Software\Anaconda\lib\site-packages\jupyter_client\manager.py", line 248, in pre_start_kernel
    self.write_connection_file()
  File "E:\Software\Anaconda\lib\site-packages\jupyter_client\connect.py", line 474, in write_connection_file
    kernel_name=self.kernel_name
  File "E:\Software\Anaconda\lib\site-packages\jupyter_client\connect.py", line 138, in write_connection_file
    with secure_write(fname) as f:
  File "E:\Software\Anaconda\lib\contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "E:\Software\Anaconda\lib\site-packages\jupyter_core\paths.py", line 435, in secure_write
    win32_restrict_file_to_user(fname)
  File "E:\Software\Anaconda\lib\site-packages\jupyter_core\paths.py", line 363, in win32_restrict_file_to_user
    import ntsecuritycon as con
ModuleNotFoundError: No module named 'ntsecuritycon'

**Comment by ShreeniketJoshi** [comment]
ModuleNotFoundError: No module named 'ntsecuritycon' this is where it is failing. I believe
