### ISSUE TITLE
Compatibility with Micromamba

### ISSUE THREAD

**Issue by epassaro** [Anaconda-Platform/nb_conda_kernels#234]
Hi! I noticed this extension does not work with `micromamba`.

My workflow consists of defining `alias conda=micromamba` and suits almost all my needs.

After looking at `manager.py` I noticed that the output of `micromamba info --json` is quite different than the expected one (a lot of different and missing keys). 

So my questions are:
1. Is there a known workaround to make this extension work with `micromamba`?
2. Should I write a patch for this?

Thanks

**Comment by mcg1969** [comment]
You might be surprised to hear this but I have no problem with the idea of making this work with micromamba. But I do think it is essential that it be well tested.

**Comment by AniAggarwal** [comment]
Haven't done much development on neither conda nor mamba but I'm happy to help test or contribute; lmk if you think there is something I can help with.

**Comment by mcg1969** [comment]
Here's what I think would be required.
- In `testbed/build.sh`, you would need to make sure that the root conda environment has `mamba` in it.
- The code would need to be modified, likely following the pattern @ken-lauer has already done, but with the ability to _configure_ whether `conda` or `mamba` is preferred. Obviously, if only one is installed, fine, go with that; but if both are installed, it would need to be selectable—if for no other reason than to facilitate testing.
- The tests in the `tests` section would need to be modified to be able to run either with `conda` or with `mamba`, selectably.

**Comment by genghisun** [comment]
Any progress?

I tried @ken-lauer 's [repo](https://github.com/ken-lauer/nb_conda_kernels/tree/enh_micromamba) but it didn't work, I don't know if I'm doing something wrong. Here are my steps:
```bash
# in micromamba env with jupyter
> git clone https://github.com/ken-lauer/nb_conda_kernels.git
> cd nb_conda_kernels/
> git checkout enh_micromamba
> pip install -e .
> python -m nb_conda_kernels.install --enable
Enabling nb_conda_kernels...
CONDA_PREFIX: /path/to/micromamba/envs/jupyter
Status: enabled
> jupyter lab
[E 2024-05-16 14:33:09.968 ServerApp] [nb_conda_kernels] couldn't call conda:
    [Errno 2] No such file or directory: 'conda'
[I 2024-05-16 14:33:10.004 ServerApp] [nb_conda_kernels] enabled, 0 kernels found
# and the kernels of other micromamba environments doesn't show up in jupyter lab webui

> python -m nb_conda_kernels list
[ListKernelSpecs] ERROR | [nb_conda_kernels] couldn't call conda:
[Errno 2] No such file or directory: 'conda'
[ListKernelSpecs] [nb_conda_kernels] enabled, 0 kernels found
Available kernels:
  python3    /path/to/micromamba/envs/jupyter/share/jupyter/kernels/python3
> jupyter kernelspec list
Available kernels:
  python3    /path/to/micromamba/envs/jupyter/share/jupyter/kernels/python3
```

**Comment by mcg1969** [comment]
I am not seeing any work being done on this. External contribution will be required. If nb_conda_kernels is essential for you, you'll need to use conda (with the libmamba solver, of course)!

**Comment by genghisun** [comment]
@ken-lauer Thanks! I made it after `ln -s micromamba .local/bin/conda`

**Comment by navneethc** [comment]
> @genghisun I have `conda` aliased to `micromamba` for users on our machines as they're used to typing it. The branch linked above, for better or worse, assumes the same is true. A soft-link in your `PATH` of `conda -> micromamba` or just having the binary named `conda` should work.
> 
> I'm well aware that the above wouldn't be acceptable for inclusion into `anaconda/nb_conda_kernels` - but it's still for my own purposes at the moment. It is working well enough on my HPC cluster but is untested elsewhere.

Would you perchance know how to do something similar in Windows 10/Powershell? I tried replicating what you said by creating a symbolic link (`conda.exe`) to `micromamba.exe`, but when I start Jupyter Lab, I get the following error.

```
PS C:\Users\Username> mm activate jupyter
(jupyter) PS C:\Users\Username> jupyter lab
[I 2024-05-18 19:21:44.411 ServerApp] jupyter_lsp | extension was successfully linked.
[I 2024-05-18 19:21:44.421 ServerApp] jupyter_server_terminals | extension was successfully linked.
[I 2024-05-18 19:21:44.435 ServerApp] jupyterlab | extension was successfully linked.
[I 2024-05-18 19:21:44.446 ServerApp] notebook | extension was successfully linked.
[I 2024-05-18 19:21:44.914 ServerApp] notebook_shim | extension was successfully linked.
Traceback (most recent call last):
  File "C:\Users\Username\micromamba\envs\jupyter\Scripts\jupyter-lab-script.py", line 10, in <module>
    sys.exit(main())
             ^^^^^^
  File "C:\Users\Username\micromamba\envs\jupyter\Lib\site-packages\jupyter_server\extension\application.py", line 616, in launch_instance
    serverapp = cls.initialize_server(argv=args)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\micromamba\envs\jupyter\Lib\site-packages\jupyter_server\extension\application.py", line 586, in initialize_server
    serverapp.initialize(
  File "C:\Users\Username\micromamba\envs\jupyter\Lib\site-packages\traitlets\config\application.py", line 118, in inner
    return method(app, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\micromamba\envs\jupyter\Lib\site-packages\jupyter_server\serverapp.py", line 2754, in initialize
    self.init_configurables()
  File "C:\Users\Username\micromamba\envs\jupyter\Lib\site-packages\jupyter_server\serverapp.py", line 2057, in init_configurables
    self.kernel_spec_manager = self.kernel_spec_manager_class(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\micromamba\envs\jupyter\Lib\site-packages\nb_conda_kernels\manager.py", line 127, in __init__
    "nb_conda_kernels | enabled, %s kernels found.", len(self._conda_kspecs)
                                                         ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\micromamba\envs\jupyter\Lib\site-packages\nb_conda_kernels\manager.py", line 389, in _conda_kspecs
    for name, info in self._all_specs().items():
                      ^^^^^^^^^^^^^^^^^
  File "C:\Users\Username\micromamba\envs\jupyter\Lib\site-packages\nb_conda_kernels\manager.py", line 267, in _all_specs
    conda_prefix = self._conda_info['conda_prefix']
                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'conda_prefix'
(jupyter) PS C:\Users\Username>
```

```
(jupyter) PS C:\Users\Username\AppData\Local\micromamba> ls


    Directory: C:\Users\Username\AppData\Local\micromamba


Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a---l            18 May     18:54              0 conda.exe
-a----            26 Mar     00:41        9015808 micromamba.exe
```

**Comment by theavey** [comment]
looks like there is a WIP PR (#279) for this, but set up a new Jupyter env with mamba=2 and Python=3.13 and found that this my conda kernels were not showing up. Would be happy to see this fixed :)

**Comment by YanzhaoW** [comment]
I createed the softlink with `ln -s ~/.local/bin/micromamba ~/.local/bin/conda` but still got an error:

```text
Traceback (most recent call last):
  File "~/micromamba/envs/r3bdev/bin/jupyter-lab", line 10, in <module>
    sys.exit(main())
             ~~~~^^
  File "~/micromamba/envs/r3bdev/lib/python3.13/site-packages/jupyter_server/extension/application.py", line 628, in launch_instance
    serverapp = cls.initialize_server(argv=args)
  File "~/micromamba/envs/r3bdev/lib/python3.13/site-packages/jupyter_server/extension/application.py", line 598, in initialize_server
    serverapp.initialize(
    ~~~~~~~~~~~~~~~~~~~~^
        argv=argv or [],
        ^^^^^^^^^^^^^^^^
        starter_extension=cls.name,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^
        find_extensions=find_extensions,
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "~/micromamba/envs/r3bdev/lib/python3.13/site-packages/traitlets/config/application.py", line 118, in inner
    return method(app, *args, **kwargs)
  File "~/micromamba/envs/r3bdev/lib/python3.13/site-packages/jupyter_server/serverapp.py", line 2834, in initialize
    self.init_configurables()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "~/micromamba/envs/r3bdev/lib/python3.13/site-packages/jupyter_server/serverapp.py", line 2098, in init_configurables
    self.kernel_spec_manager = self.kernel_spec_manager_class(
                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        parent=self,
        ^^^^^^^^^^^^
    )
    ^
  File "~/micromamba/envs/r3bdev/lib/python3.13/site-packages/nb_conda_kernels/manager.py", line 127, in __init__
    "nb_conda_kernels | enabled, %s kernels found.", len(self._conda_kspecs)
                                                         ^^^^^^^^^^^^^^^^^^
  File "~/micromamba/envs/r3bdev/lib/python3.13/site-packages/nb_conda_kernels/manager.py", line 389, in _conda_kspecs
    for name, info in self._all_specs().items():
                      ~~~~~~~~~~~~~~~^^
  File "~/micromamba/envs/r3bdev/lib/python3.13/site-packages/nb_conda_kernels/manager.py", line 267, in _all_specs
    conda_prefix = self._conda_info['conda_prefix']
                   ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'conda_prefix'
```

This seems environment variable `CONDA_PREFIX` must be defined.

**Comment by zhangjiakouzf** [comment]
> I createed the softlink with `ln -s ~/.local/bin/micromamba ~/.local/bin/conda` but still got an error:
> 
> ```
> Traceback (most recent call last):
>   File "~/micromamba/envs/r3bdev/bin/jupyter-lab", line 10, in <module>
>     sys.exit(main())
>              ~~~~^^
>   File "~/micromamba/envs/r3bdev/lib/python3.13/site-packages/jupyter_server/extension/application.py", line 628, in launch_instance
>     serverapp = cls.initialize_server(argv=args)
>   File "~/micromamba/envs/r3bdev/lib/python3.13/site-packages/jupyter_server/extension/application.py", line 598, in initialize_server
>     serverapp.initialize(
>     ~~~~~~~~~~~~~~~~~~~~^
>         argv=argv or [],
>         ^^^^^^^^^^^^^^^^
>         starter_extension=cls.name,
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         find_extensions=find_extensions,
>         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>     )
>     ^
>   File "~/micromamba/envs/r3bdev/lib/python3.13/site-packages/traitlets/config/application.py", line 118, in inner
>     return method(app, *args, **kwargs)
>   File "~/micromamba/envs/r3bdev/lib/python3.13/site-packages/jupyter_server/serverapp.py", line 2834, in initialize
>     self.init_configurables()
>     ~~~~~~~~~~~~~~~~~~~~~~~^^
>   File "~/micromamba/envs/r3bdev/lib/python3.13/site-packages/jupyter_server/serverapp.py", line 2098, in init_configurables
>     self.kernel_spec_manager = self.kernel_spec_manager_class(
>                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
>         parent=self,
>         ^^^^^^^^^^^^
>     )
>     ^
>   File "~/micromamba/envs/r3bdev/lib/python3.13/site-packages/nb_conda_kernels/manager.py", line 127, in __init__
>     "nb_conda_kernels | enabled, %s kernels found.", len(self._conda_kspecs)
>                                                          ^^^^^^^^^^^^^^^^^^
>   File "~/micromamba/envs/r3bdev/lib/python3.13/site-packages/nb_conda_kernels/manager.py", line 389, in _conda_kspecs
>     for name, info in self._all_specs().items():
>                       ~~~~~~~~~~~~~~~^^
>   File "~/micromamba/envs/r3bdev/lib/python3.13/site-packages/nb_conda_kernels/manager.py", line 267, in _all_specs
>     conda_prefix = self._conda_info['conda_prefix']
>                    ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
> KeyError: 'conda_prefix'
> ```
> 
> This seems environment variable `CONDA_PREFIX` must be defined.

the same issue with python3.14 and micromamba
