### ISSUE TITLE
Kernels does not show in Jupyterlab

### ISSUE THREAD

**Issue by hadim** [Anaconda-Platform/nb_conda_kernels#60]
Please see there for the details : 

https://github.com/jupyterlab/jupyterlab/issues/1557

**Comment by hadim** [comment]
(by the way did you consider making this default in Anaconda ?)

**Comment by hadim** [comment]
Ok here is something interesting that might help the debugging.

When I start `jupyter notebook` and then go to http://127.0.0.1:8888/lab I can see the kernels installed by `nb_conda_kernels`.

Now if I start jupyterlab with `jupyter lab`, I can't see the kernels.

Here is the log for `jupyter notebook` : 

```
[I 16:00:20.517 NotebookApp] [nb_conda_kernels] enabled, 4 kernels found
[I 16:00:20.567 NotebookApp] Loading IPython parallel extension
[I 16:00:20.604 NotebookApp] JupyterLab alpha preview extension loaded from /home/hadim/local/conda/lib/python3.5/site-packages/jupyterlab
[I 16:00:20.607 NotebookApp] Serving notebooks from local directory: /home/hadim
[I 16:00:20.607 NotebookApp] 0 active kernels 
[I 16:00:20.607 NotebookApp] The Jupyter Notebook is running at: http://localhost:8888/?token=0f573392ad62a8714155c68c1bef07cecd39bd7e941c6353
[I 16:00:20.607 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 16:00:20.611 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=0f573392ad62a8714155c68c1bef07cecd39bd7e941c6353
Using PPAPI flash.
--disable-new-tab-first-run --enable-user-scripts --ppapi-flash-path=/usr/lib/adobe-flashplugin/libpepflashplayer.so --ppapi-flash-version=
Created new window in existing browser session.
[I 16:00:21.546 NotebookApp] Accepting one-time-token-authenticated connection from 127.0.0.1
[I 16:00:22.279 NotebookApp] 302 GET /api/sessions?1485550822270 (127.0.0.1) 1.00ms
[I 16:00:22.281 NotebookApp] 302 GET /api/terminals?1485550822272 (127.0.0.1) 1.08ms
```

and for `jupyter lab` : 

```
[W 16:03:47.554 LabApp] All authentication is disabled.  Anyone who can connect to this server will be able to run code.
[I 16:03:47.562 LabApp] Serving notebooks from local directory: /home/hadim/Documents/Hadrien/Google_Drive/Documents
[I 16:03:47.562 LabApp] 0 active kernels 
[I 16:03:47.563 LabApp] The Jupyter Notebook is running at: http://localhost:8888/
[I 16:03:47.563 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 16:17:41.884 LabApp] Creating new notebook in /Code/notebooks/Sandbox
[W 16:17:44.046 LabApp] delete /Code/notebooks/Sandbox/Untitled5.ipynb
```

Looks like `[nb_conda_kernels] enabled, 4 kernels found` is not loaded with `jupyter lab`.

Do you still think this issue belong to `nb_conda_kernels` @blink1073 ?

**Comment by blink1073** [comment]
Ah, we have been tweaking the way config in JupyterLab works, apparently it caused this issue.  We're releasing 0.15 on Monday that should fix this.  cf https://github.com/jupyterlab/jupyterlab/pull/1555

**Comment by hadim** [comment]
Nice to hear.

**Comment by damianavila** [comment]
> (by the way did you consider making this default in Anaconda ?)

Just a comment, `nb_conda_kernels` and other extension were provided by default in Anaconda in the past, but we have decided to change that in Anaconda 4.3 (just released). Still the extensions will be available at the defaults channel for those who want to use it.

**Comment by hadim** [comment]
Ok.

**Comment by tdrobbin** [comment]
I'm running into this exact same error after creating a new environment and installing jupyter lab 0.30.5=py36_0 from the main conda channel with:
```
conda install jupyterlab
```

The Notebook recognizes all of my conda environments but Lab does not. More specifically I'm getting the following readout when running ```jupyter lab```:
```
(sda) Tylers-MacBook-Pro:sda tdrobbin$ jupyter lab
Traceback (most recent call last):
  File "/Users/tdrobbin/anaconda/envs/sda/bin/conda", line 7, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
[E 00:22:00.401 LabApp] [nb_conda_kernels] couldn't call conda:
    Command '['conda', 'info', '--json']' returned non-zero exit status 1.
[I 00:22:00.402 LabApp] [nb_conda_kernels] enabled, 0 kernels found
[I 00:22:01.397 LabApp] [nb_anacondacloud] enabled
[I 00:22:01.401 LabApp] [nb_conda] enabled
[I 00:22:01.505 LabApp] ✓ nbpresent HTML export ENABLED
[W 00:22:01.505 LabApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[W 00:22:01.505 LabApp] JupyterLab server extension not enabled, manually loading...
[I 00:22:01.515 LabApp] JupyterLab alpha preview extension loaded from /Users/tdrobbin/anaconda/envs/sda/lib/python3.6/site-packages/jupyterlab
[I 00:22:01.515 LabApp] JupyterLab application directory is /Users/tdrobbin/anaconda/envs/sda/share/jupyter/lab
[I 00:22:01.530 LabApp] Serving notebooks from local directory: /Users/tdrobbin/Documents/git_standalone/sda
[I 00:22:01.530 LabApp] 0 active kernels
[I 00:22:01.530 LabApp] The Jupyter Notebook is running at:
[I 00:22:01.530 LabApp] http://localhost:8888/?token=b42c5df6af9ee3452e7cb7d781c60bbe99b3cc8ab8de3f4f
[I 00:22:01.530 LabApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 00:22:01.533 LabApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8888/?token=b42c5df6af9ee3452e7cb7d781c60bbe99b3cc8ab8de3f4f
0:96: execution error: "http://localhost:8888/lab?token=a89e1e59eba3f65f18599af725009090c035624f942dfeaa" doesn’t understand the “open location” message. (-1708)
```

Here's some of my environment info in case it's helpful:

```
- ipykernel=4.7.0=py36h2f9c1c0_0
- ipython=6.2.1=py36h3dda519_1
- jupyter_client=5.1.0=py36hf6c435f_0
- jupyter_core=4.4.0=py36h79cf704_0
- jupyterlab=0.30.5=py36_0
- jupyterlab_launcher=0.6.0=py36_0
- nb_conda=2.2.1=py36h349edbb_0
- nb_conda_kernels=2.1.0=py36_0
- notebook=5.2.2=py36h124cd7f_0
```

**Comment by damianavila** [comment]
When you start the `jupyter notebook` do you see the same traceback?

**Comment by tdrobbin** [comment]
similar, expect it seems to be detecting my conda enviroments. Here's the traceback for the notebook
```
(sda) Tylers-MacBook-Pro:sda tdrobbin$ jupyter notebook
[I 18:45:05.537 NotebookApp] [nb_conda_kernels] enabled, 12 kernels found
[I 18:45:06.396 NotebookApp] The port 8888 is already in use, trying another port.
[I 18:45:06.396 NotebookApp] The port 8889 is already in use, trying another port.
[I 18:45:06.484 NotebookApp] [nb_anacondacloud] enabled
[I 18:45:06.489 NotebookApp] [nb_conda] enabled
[I 18:45:06.594 NotebookApp] ✓ nbpresent HTML export ENABLED
[W 18:45:06.594 NotebookApp] ✗ nbpresent PDF export DISABLED: No module named 'nbbrowserpdf'
[I 18:45:06.598 NotebookApp] Serving notebooks from local directory: /Users/tdrobbin/Documents/git_standalone/sda
[I 18:45:06.598 NotebookApp] 0 active kernels
[I 18:45:06.599 NotebookApp] The Jupyter Notebook is running at:
[I 18:45:06.599 NotebookApp] http://localhost:8890/?token=0af2c42547a4f92e88ba3c221cfadc84313c5a47cbafb71e
[I 18:45:06.599 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[C 18:45:06.604 NotebookApp] 
    
    Copy/paste this URL into your browser when you connect for the first time,
    to login with a token:
        http://localhost:8890/?token=0af2c42547a4f92e88ba3c221cfadc84313c5a47cbafb71e
0:97: execution error: "http://localhost:8890/tree?token=ae1083afeac3af49b69f8442ac7414f9c1671fc6faf01902" doesn’t understand the “open location” message. (-1708)
```

**Comment by damianavila** [comment]
```
Traceback (most recent call last):
  File "/Users/tdrobbin/anaconda/envs/sda/bin/conda", line 7, in <module>
    from conda.cli import main
ModuleNotFoundError: No module named 'conda'
```

That error is weird, I was expecting you see the same traceback with the notebook.

@blink1073, any ideas? Anything specific in Jupyter Lab that can trigger this behavior? (I don't think so, btw).

**Comment by blink1073** [comment]
@tdrobbin, what are the outputs of `which jupyter-lab && which jupyter-notebook`?

**Comment by tdrobbin** [comment]
Sure, here's the output:
```
(sda) Tylers-MacBook-Pro:sda tdrobbin$  which jupyter-lab && which jupyter-notebook
/Users/tdrobbin/anaconda/envs/sda/bin/jupyter-lab
/Users/tdrobbin/anaconda/envs/sda/bin/jupyter-notebook
```

**Comment by blink1073** [comment]
Thanks!  No, I can't think of anything JupyterLab specific then.

**Comment by tdrobbin** [comment]
I'm on macOS and the problem seems to have been that I commented out the line that used to like this in my .bash_profile:

```
export PATH="/Users/tdrobbin/anaconda/bin:$PATH"
```

following the instructions below, after updating conda recently:

```
Tylers-MacBook-Pro:~ tdrobbin$ conda activate base

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
If your shell is Bash or a Bourne variant, enable conda for the current user with

    $ echo ". /Users/tdrobbin/anaconda/etc/profile.d/conda.sh" >> ~/.bash_profile

or, for all users, enable conda with

    $ sudo ln -s /Users/tdrobbin/anaconda/etc/profile.d/conda.sh /etc/profile.d/conda.sh

The options above will permanently enable the 'conda' command, but they do NOT
put conda's base (root) environment on PATH.  To do so, run

    $ conda activate

in your terminal, or to put the base environment on PATH permanently, run

    $ echo "conda activate" >> ~/.bash_profile

Previous to conda 4.4, the recommended way to activate conda was to modify PATH in
your ~/.bash_profile file.  You should manually remove the line that looks like

    export PATH="/Users/tdrobbin/anaconda/bin:$PATH"

^^^ The above line should NO LONGER be in your ~/.bash_profile file! ^^^
```

So I un-commented out ```export PATH="/Users/tdrobbin/anaconda/bin:$PATH"```. the only downside seems to be that i have call ```source``` to activate/deactivate my conda environments instead of ```conda```. Everything else with conda and my environments seems to be working smoothly and I know have access to all my environments in jupyter lab

**Comment by jorgejgleandro** [comment]
base> activate your_env
your_env> python -m ipykernel install --user --name your_env --display-name your_env
