### ISSUE TITLE
conda 4.4.7 does not work with nb_conda_kernels in new/reinstalled envs

### ISSUE THREAD

**Issue by michaelaye** [Anaconda-Platform/nb_conda_kernels#73]
In base env my launch log for a jupyter notebook looks like that:

```bash
(stable) └─❱❱❱ conda activate base                                                   +9035 17:51 ❰─┘

┌─( ~/D/src )────────────────────────────────────────────────────────────────────────( @macd2860 )─┐
(base) └─❱❱❱ jn .                                                                    +9036 17:51 ❰─┘
[I 17:51:31.745 NotebookApp] [nb_conda_kernels] enabled, 8 kernels found
[I 17:51:32.046 NotebookApp] Loading IPython parallel extension
[I 17:51:32.063 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.3.0
[I 17:51:32.066 NotebookApp] Serving notebooks from local directory: /Users/klay6683/Dropbox/src
[I 17:51:32.066 NotebookApp] 0 active kernels
```

I recently reinstalled by `stable` setup, which is a Python 3.6 env with all my everyday packages and no GH master stuff.
Since the reinstall, `nb_conda_kernels` can't call conda from within the `stable` env:

```bash
(base) └─❱❱❱ conda activate stable                                                   +9037 17:52 ❰─┘

┌─( ~/D/src )────────────────────────────────────────────────────────────────────────( @macd2860 )─┐
(stable) └─❱❱❱ jn .                                                                  +9038 17:52 ❰─┘
[E 17:52:50.245 NotebookApp] [nb_conda_kernels] couldn't call conda:
    [Errno 2] No such file or directory: 'conda': 'conda'
[I 17:52:50.246 NotebookApp] [nb_conda_kernels] enabled, 0 kernels found
[I 17:52:50.540 NotebookApp] Loading IPython parallel extension
[I 17:52:50.557 NotebookApp] [jupyter_nbextensions_configurator] enabled 0.3.0
[I 17:52:50.560 NotebookApp] Serving notebooks from local directory: /Users/klay6683/Dropbox/src
[I 17:52:50.560 NotebookApp] 0 active kernels
```

while my older envs still work fine, e.g. my Python 3.5 env.

I noticed that I can of course run my work from the base env because my kernels from the other envs are being found there, but imagine it wouldn't be working there as well, then I couldn't work at all, because I don't recall anymore how to manually install kernels, so scary indeed.

I'm running these on a macOS 10.12.6 with miniconda3 and conda-forge as default.

**Comment by michaelaye** [comment]
This is now blocking my work on another machine, please help! No env discovers the installed kernels anymore.

**Comment by michaelaye** [comment]
i went back to conda 4.3.x and things are working.

**Comment by goweiting** [comment]
Hi, im experiencing the same problem after upgrading to conda 4.4.7. was working on 4.3.30 and nb_conda_kernel was able to detect all the kernels from different packages.

**Comment by dartdog** [comment]
Cross referencing https://github.com/jupyter/jupyter_client/issues/338

**Comment by michaelaye** [comment]
@goweiting did you directly go to 4.4.7 from 4.3.x? Because I tried 4.4.7 now again after a complete wipe of my miniconda folder, and everything seems to be working now.

On my side, this issue could be closed.

**Comment by goweiting** [comment]
@michaelaye some of my systems are still running processes so i am not ready to shut them down yet. 
For the one of my Ubuntu, removing:
`_nb_ext_conf` 
(```conda remove -n <env_name> _nb_ext_conf```), 
fixes the problem and am able to see different environment, including IRKernel.

**Comment by benbovy** [comment]
I think this issue has not been fixed yet.

Running from jupyter,`nb_conda_kernels` tries to call the `conda` executable to get information about all the environments.

The problem is that since conda 4.4 it appears there is no link to the `conda` executable added to new/reinstalled envs, which therefore cannot be found in `$PATH`, hence the error above.

For environments that have been created before conda 4.4 it still works because a link to the `conda` executable is still present in those envs. This also works with the base environment since the conda executable is installed in that env.

A workaround for new/reinstalled envs would be for example to manually create a symlink to the conda executable in their `bin` folders.

A cleaner solution would be that `nb_conda_kernels` uses the `$CONDA_EXE` env variable to find the conda exectuable.

xref: https://github.com/jupyterlab/jupyterlab/issues/4598

**Comment by tjd2002** [comment]
@benbovy Thanks very much for the workaround and the fix. I had the same issue in conda 4.5.3 in a non-base env:  nb_conda was not usable without your fix.

**Comment by mcg1969** [comment]
I'm trying to address this in #80

**Comment by mcg1969** [comment]
Actually, #82 is going to address this.

**Comment by cecilialee** [comment]
Thanks @goweiting your code works for me! In my case I installed the IRkernel and I cannot find my kernels anymore.

**Comment by michaelaye** [comment]
this is still the same issue with nb_conda_kernels 2.1.0 ?

**Comment by michaelaye** [comment]
was this fixed in 2.1.1? If yes, I'm not seeing that version on any osx-64 channel?

**Comment by tjd2002** [comment]
Not available for linux either:
```
$ conda search nb_conda_kernels'>=2.1[subdir=osx-64]' -c defaults -c conda-forge
Loading channels: done
# Name                  Version           Build  Channel
nb_conda_kernels           2.1.0          py27_0  pkgs/free
nb_conda_kernels           2.1.0          py27_0  conda-forge
nb_conda_kernels           2.1.0          py35_0  pkgs/free
nb_conda_kernels           2.1.0          py35_0  conda-forge
nb_conda_kernels           2.1.0          py36_0  pkgs/free
nb_conda_kernels           2.1.0          py36_0  conda-forge

$ conda search nb_conda_kernels'>=2.1[subdir=linux-64]' -c defaults -c conda-forge
Loading channels: done
# Name                  Version           Build  Channel
nb_conda_kernels           2.1.0          py27_0  pkgs/free
nb_conda_kernels           2.1.0          py27_0  conda-forge
nb_conda_kernels           2.1.0          py35_0  pkgs/free
nb_conda_kernels           2.1.0          py35_0  conda-forge
nb_conda_kernels           2.1.0          py36_0  pkgs/free
nb_conda_kernels           2.1.0          py36_0  conda-forge
```
@mcg1969 What's involved in shipping your latest changes?

**Comment by mcg1969** [comment]
I've submitted a conda-forge PR
https://github.com/conda-forge/nb_conda_kernels-feedstock/pull/18
I don't know what is involved in getting it merged.

**Comment by tjd2002** [comment]
Thanks @mcg1969. It looks like the 2.1.1 packages are all up on conda-forge now!
https://anaconda.org/conda-forge/nb_conda_kernels

However, after installing this package on my mac, the extension is not enabled by default. I have to run:
`python -m nb_conda_kernels.install --enable`

This used to be done in a post-link script that was shipped in the package. Is this change intentional?

[Also, if Continuum is not going to update this package in defaults, should it be removed from there?]

**Comment by tjd2002** [comment]
So: the problem is that as of #82 the `post-link.sh` and `pre-link.sh` scripts are no longer in conda-forge's conda-recipe folder, so they will only get properly installed when the package is built locally. 

E.g. when I build the 2.1.1 package locally on my mac, the scripts are included:
```
$ tar -tjf ~/anaconda3/conda-bld/osx-64/nb_conda_kernels-2.1.1-py36_0.tar.bz2 |sort
bin/.nb_conda_kernels-post-link.sh
bin/.nb_conda_kernels-pre-unlink.sh
info/LICENSE.txt
info/about.json
[...]
```

But the version shipped by conda-forge does not include these scripts:
```
$ tar -tjf ~/anaconda3/pkgs/nb_conda_kernels-2.1.1-py36_0.tar.bz2
info/index.json
info/LICENSE.txt
```

This is not caught by any tests because the package builds and tests correctly as part of this repo, and conda-forge doesn't seem to run the package's own tests (see https://github.com/conda-forge/nb_conda_kernels-feedstock/blob/master/.travis.yml)

The solution would seem to be: Find a way to coerce conda-forge to include the post-link and pre-link scripts from the source repo. (This could be as simple as copying them over to the conda-recipe folder, but I'm not sure the best way to do this).

I'll also open an issue on the feedstock page to track this.

**Comment by GPhilo** [comment]
It seems the issue is not completely resolved yet (I'm using nb_conda_kernels version 2.1.1).
Opening the Conda tab in Jupyter raises "An error occurred while retrieving package information.".

The log is as follows:
```
[E 12:01:51.653 NotebookApp] Uncaught exception GET /conda/environments?_=1536228110147 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/conda/environments?_=1536228110147', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/handlers.py", line 716, in wrapper
        return method(self, *args, **kwargs)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/nb_conda/handlers.py", line 51, in get
        self.finish(json.dumps(self.env_manager.list_envs()))
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/nb_conda/envmanager.py", line 67, in list_envs
        info = self.clean_conda_json(self._execute('conda info --json'))
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/nb_conda/envmanager.py", line 53, in _execute
        output = check_output(cmdline)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 403, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'conda': 'conda'
[W 12:01:51.657 NotebookApp] Unhandled error
[E 12:01:51.657 NotebookApp] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|64532e4b|5a8f8bf30116ab97ccb0479dd441e9f3|1536226908",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36",
      "Referer": "http://localhost:8889/tree",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "it,en-US;q=0.9,en;q=0.8,en-GB;q=0.7",
      "Cookie": "_xsrf=2|64532e4b|5a8f8bf30116ab97ccb0479dd441e9f3|1536226908; username-localhost-8889=\"2|1:0|10:1536228109|23:username-localhost-8889|44:NGFiZTdmNWM0ZTliNGViYWE1Y2FhOTU1MDU3YWI3MTQ=|e16431064a03ce415bb2038897de55e552e3e8ee6cff71b63d6baff9aa1c2d5c\""
    }
[E 12:01:51.657 NotebookApp] 500 GET /conda/environments?_=1536228110147 (127.0.0.1) 9.51ms referer=http://localhost:8889/tree
[E 12:01:51.664 NotebookApp] Uncaught exception GET /conda/packages/available?_=1536228110148 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/conda/packages/available?_=1536228110148', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/handlers.py", line 716, in wrapper
        return method(self, *args, **kwargs)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/nb_conda/handlers.py", line 230, in get
        data = searcher.list_available(self)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/nb_conda/handlers.py", line 213, in list_available
        bufsize=4096)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'conda': 'conda'
[W 12:01:51.665 NotebookApp] Unhandled error
[E 12:01:51.665 NotebookApp] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|64532e4b|5a8f8bf30116ab97ccb0479dd441e9f3|1536226908",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36",
      "Referer": "http://localhost:8889/tree",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "it,en-US;q=0.9,en;q=0.8,en-GB;q=0.7",
      "Cookie": "_xsrf=2|64532e4b|5a8f8bf30116ab97ccb0479dd441e9f3|1536226908; username-localhost-8889=\"2|1:0|10:1536228109|23:username-localhost-8889|44:NGFiZTdmNWM0ZTliNGViYWE1Y2FhOTU1MDU3YWI3MTQ=|e16431064a03ce415bb2038897de55e552e3e8ee6cff71b63d6baff9aa1c2d5c\""
    }
[E 12:01:51.665 NotebookApp] 500 GET /conda/packages/available?_=1536228110148 (127.0.0.1) 6.15ms referer=http://localhost:8889/tree
[E 12:03:23.364 NotebookApp] Uncaught exception GET /conda/environments?_=1536228110152 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/conda/environments?_=1536228110152', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/handlers.py", line 716, in wrapper
        return method(self, *args, **kwargs)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/nb_conda/handlers.py", line 51, in get
        self.finish(json.dumps(self.env_manager.list_envs()))
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/nb_conda/envmanager.py", line 67, in list_envs
        info = self.clean_conda_json(self._execute('conda info --json'))
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/nb_conda/envmanager.py", line 53, in _execute
        output = check_output(cmdline)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 336, in check_output
        **kwargs).stdout
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 403, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'conda': 'conda'
[W 12:03:23.365 NotebookApp] Unhandled error
[E 12:03:23.366 NotebookApp] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|64532e4b|5a8f8bf30116ab97ccb0479dd441e9f3|1536226908",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36",
      "Referer": "http://localhost:8889/tree",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "it,en-US;q=0.9,en;q=0.8,en-GB;q=0.7",
      "Cookie": "_xsrf=2|64532e4b|5a8f8bf30116ab97ccb0479dd441e9f3|1536226908; username-localhost-8889=\"2|1:0|10:1536228109|23:username-localhost-8889|44:NGFiZTdmNWM0ZTliNGViYWE1Y2FhOTU1MDU3YWI3MTQ=|e16431064a03ce415bb2038897de55e552e3e8ee6cff71b63d6baff9aa1c2d5c\""
    }
[E 12:03:23.367 NotebookApp] 500 GET /conda/environments?_=1536228110152 (127.0.0.1) 7.50ms referer=http://localhost:8889/tree
[E 12:03:23.373 NotebookApp] Uncaught exception GET /conda/packages/available?_=1536228110153 (127.0.0.1)
    HTTPServerRequest(protocol='http', host='localhost:8889', method='GET', uri='/conda/packages/available?_=1536228110153', version='HTTP/1.1', remote_ip='127.0.0.1')
    Traceback (most recent call last):
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 1590, in _execute
        result = method(*self.path_args, **self.path_kwargs)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/tornado/web.py", line 3006, in wrapper
        return method(self, *args, **kwargs)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/notebook/base/handlers.py", line 716, in wrapper
        return method(self, *args, **kwargs)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/nb_conda/handlers.py", line 230, in get
        data = searcher.list_available(self)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/site-packages/nb_conda/handlers.py", line 213, in list_available
        bufsize=4096)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 709, in __init__
        restore_signals, start_new_session)
      File "/home/slr/anaconda3/envs/tensorflow/lib/python3.6/subprocess.py", line 1344, in _execute_child
        raise child_exception_type(errno_num, err_msg, err_filename)
    FileNotFoundError: [Errno 2] No such file or directory: 'conda': 'conda'
[W 12:03:23.374 NotebookApp] Unhandled error
[E 12:03:23.374 NotebookApp] {
      "Host": "localhost:8889",
      "Connection": "keep-alive",
      "Accept": "application/json, text/javascript, */*; q=0.01",
      "X-Requested-With": "XMLHttpRequest",
      "X-Xsrftoken": "2|64532e4b|5a8f8bf30116ab97ccb0479dd441e9f3|1536226908",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.81 Safari/537.36",
      "Referer": "http://localhost:8889/tree",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "it,en-US;q=0.9,en;q=0.8,en-GB;q=0.7",
      "Cookie": "_xsrf=2|64532e4b|5a8f8bf30116ab97ccb0479dd441e9f3|1536226908; username-localhost-8889=\"2|1:0|10:1536228109|23:username-localhost-8889|44:NGFiZTdmNWM0ZTliNGViYWE1Y2FhOTU1MDU3YWI3MTQ=|e16431064a03ce415bb2038897de55e552e3e8ee6cff71b63d6baff9aa1c2d5c\""
    }
[E 12:03:23.375 NotebookApp] 500 GET /conda/packages/available?_=1536228110153 (127.0.0.1) 6.28ms referer=http://localhost:8889/tree
```

The relevant part is: `FileNotFoundError: [Errno 2] No such file or directory: 'conda': 'conda'`
