### ISSUE TITLE
nb_conda_kernels not found when using nbconvert --execute

### ISSUE THREAD

**Issue by croth1** [Anaconda-Platform/nb_conda_kernels#77]
I am trying to run a notebook that uses a kernel from an automatically registered environment like this:

`jupyter nbconvert --to notebook --execute advanced_mapping.ipynb`

I am getting:

```
[NbConvertApp] Converting notebook advanced_mapping.ipynb to notebook
[NbConvertApp] Executing notebook with kernel: testenv
Traceback (most recent call last):
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/jupyter_client/kernelspec.py", line 201, in get_kernel_spec
    resource_dir = d[kernel_name.lower()]
KeyError: 'conda-env-testenv-py'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/croth1/miniconda2/envs/sci36/bin/jupyter-nbconvert", line 6, in <module>
    sys.exit(nbconvert.nbconvertapp.main())
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/jupyter_core/application.py", line 267, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 305, in start
    self.convert_notebooks()
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 473, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 444, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/nbconvert/nbconvertapp.py", line 373, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 171, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 189, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/nbconvert/exporters/notebook.py", line 31, in from_notebook_node
    nb_copy, resources = super(NotebookExporter, self).from_notebook_node(nb, resources, **kw)
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 131, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/nbconvert/exporters/exporter.py", line 308, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb,resources)
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 207, in preprocess
    cwd=path)
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/nbconvert/preprocessors/execute.py", line 188, in start_new_kernel
    km.start_kernel(**kwargs)
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/jupyter_client/manager.py", line 244, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/jupyter_client/manager.py", line 175, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/jupyter_client/manager.py", line 87, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/home/croth1/miniconda2/envs/sci36/lib/python3.6/site-packages/jupyter_client/kernelspec.py", line 203, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named conda-env-testenv-py

**Comment by mpacer** [comment]
Note this issue discussing these problems on nbconvert: https://github.com/jupyter/nbconvert/issues/515

**Comment by mcg1969** [comment]
It's not clear to me that there is anything that can be done about this within `nb_conda_kernels` itself without monkeypatching the `nbconvert` package.

**Comment by mcg1969** [comment]
I do have an idea on how `nb_conda_kernels` could be extended to handle issues like this. @fcollonval, you might be interested in this, or maybe even in trying to implement it.

As you may know, `nb_conda_kernels` operates by dynamically generating `kernelspec` data from the conda environments has access to. This works with Jupyter notebooks because it is possible to override the kernel discovery mechanism in notebooks. Unfortunately, this is not possible in other applications, including `jupyter console` and `nbconvert`.

However, what if `nb_conda_kernels` were modified to _cache its auto-generated kernelspecs on disk_, in the standard Jupyter search location? Then, as long as `nb_conda_kernels` has been run at least once, _All other Jupyter modules_ that search the standard kernel location will find them.

There are two downsides to this approach, in my view. One is that it might take an undesirable amount of time to read, modify, and write this cache. We won't really know that for sure unless we try. But the other reason is that it requires running the extension at least once before using `nbconvert` or `jupyter console`, and re-running it whenever the conda environments change. I propose that this be solved by creating an _activation script_ for `nb_conda_kernels`. So every time the environment containing this package is activated, it re-scans the environment set and makes changes as necessary.

Indeed, if we were to do this, it could become the _primary_ mechanism by which Jupyter discovers kernels.

**Comment by mcg1969** [comment]
PR #104 takes a different approach to solving this problem: it patches `jupyter_client` itself :-)

**Comment by jraviotta** [comment]
Are there any resolutions to this issue? I can't get `nbconvert` to execute a notebook and save to .html.

<p><details><summary>My environment on WSL</summary>  

```  
$ conda list
# packages in environment at /usr/share/miniconda3:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                   pypi_0    pypi
arrow                     0.13.2                   py36_0    conda-forge
asn1crypto                0.24.0                py36_1003    conda-forge
astroid                   2.2.5                    py36_0    conda-forge
attrs                     19.1.0                     py_0    conda-forge
awscli                    1.16.164                 pypi_0    pypi
babel                     2.6.0                    pypi_0    pypi
backcall                  0.1.0                      py_0    conda-forge
binaryornot               0.4.4                      py_1    conda-forge
bleach                    3.1.0                      py_0    conda-forge
botocore                  1.12.154                 pypi_0    pypi
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py36_0    conda-forge
cffi                      1.12.3           py36h8022711_0    conda-forge
chardet                   3.0.4                 py36_1003    conda-forge
click                     7.0                        py_0    conda-forge
colorama                  0.3.9                    pypi_0    pypi
conda                     4.6.14                   py36_0    conda-forge
conda-env                 2.6.0                         1    conda-forge
cookiecutter              1.6.0                 py36_1000    conda-forge
coverage                  4.5.3                    pypi_0    pypi
cryptography              2.6.1            py36h72c5cf5_0    conda-forge
cryptography-vectors      2.6.1                      py_0    conda-forge
cycler                    0.10.0                   pypi_0    pypi
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
docutils                  0.14                     pypi_0    pypi
entrypoints               0.3                   py36_1000    conda-forge
expat                     2.2.5             hf484d3e_1002    conda-forge
flake8                    3.7.7                    pypi_0    pypi
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
future                    0.17.1                py36_1000    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3            hf63aee3_1001    conda-forge
gmp                       6.1.2             hf484d3e_1000    conda-forge
gst-plugins-base          1.14.4            hdf3bae2_1001    conda-forge
gstreamer                 1.14.4            h66beb1c_1001    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py36_1000    conda-forge
imagesize                 1.1.0                    pypi_0    pypi
ipykernel                 5.1.1            py36h24bf2e0_0    conda-forge
ipython                   7.5.0            py36h24bf2e0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
isort                     4.3.20                   py36_0    conda-forge
jedi                      0.13.3                   py36_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jinja2-time               0.2.0                      py_2    conda-forge
jmespath                  0.9.4                    pypi_0    pypi
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.0.1                    py36_0    conda-forge
jupyter                   1.0.0                      py_2    conda-forge
jupyter-contrib-core      0.3.3                    pypi_0    pypi
jupyter-contrib-nbextensions 0.5.1                    pypi_0    pypi
jupyter-highlight-selected-word 0.2.0                    pypi_0    pypi
jupyter-latex-envs        1.4.6                    pypi_0    pypi
jupyter-nbextensions-configurator 0.4.1                    pypi_0    pypi
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_console           6.0.0                      py_0    conda-forge
jupyter_contrib_core      0.3.3                      py_2    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
jupyter_highlight_selected_word 0.2.0                 py36_1000    conda-forge
jupyter_latex_envs        1.4.4                 py36_1000    conda-forge
jupyterlab                0.35.6                   py36_0    conda-forge
jupyterlab_server         0.2.0                      py_0    conda-forge
jupyterthemes             0.20.0                   pypi_0    pypi
kiwisolver                1.0.1                    pypi_0    pypi
lazy-object-proxy         1.4.1            py36h516909a_0    conda-forge
lesscpy                   0.13.0                   pypi_0    pypi
libedit                   3.1.20170329      hf8c457e_1001    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libiconv                  1.15              h516909a_1005    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libsodium                 1.0.16            h14c3975_1001    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_0    conda-forge
libxslt                   1.1.32            h4785a14_1002    conda-forge
lxml                      4.3.0                    pypi_0    pypi
markupsafe                1.1.1            py36h14c3975_0    conda-forge
matplotlib                3.0.2                    pypi_0    pypi
mccabe                    0.6.1                    pypi_0    pypi
mistune                   0.8.4           py36h14c3975_1000    conda-forge
nb_conda                  2.2.1                    py36_2    conda-forge
nb_conda_kernels          2.2.2                    py36_0    conda-forge
nbconvert                 5.5.0                      py_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
nodejs                    11.14.0              he1b5a44_1    conda-forge
notebook                  5.7.8                    py36_0    conda-forge
numpy                     1.16.0                   pypi_0    pypi
openssl                   1.1.1b               h14c3975_1    conda-forge
packaging                 19.0                     pypi_0    pypi
pandoc                    2.7.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.4.0                      py_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pexpect                   4.7.0                    py36_0    conda-forge
pickleshare               0.7.5                 py36_1000    conda-forge
pip                       19.1.1                   pypi_0    pypi
ply                       3.11                     pypi_0    pypi
poyo                      0.4.2                      py_0    conda-forge
prometheus_client         0.6.0                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pyasn1                    0.4.5                    pypi_0    pypi
pycodestyle               2.5.0                    pypi_0    pypi
pycosat                   0.6.3           py36h14c3975_1001    conda-forge
pycparser                 2.19                     py36_1    conda-forge
pyflakes                  2.1.1                    pypi_0    pypi
pygments                  2.4.0                      py_0    conda-forge
pylint                    2.3.1                    py36_0    conda-forge
pyopenssl                 19.0.0                   py36_0    conda-forge
pyparsing                 2.3.1                    pypi_0    pypi
pyqt                      5.9.2            py36hcca6a23_0    conda-forge
pyrsistent                0.15.2           py36h516909a_0    conda-forge
pysocks                   1.7.0                    py36_0    conda-forge
python                    3.6.7             h381d211_1004    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-dotenv             0.10.2                   pypi_0    pypi
pytz                      2019.1                   pypi_0    pypi
pyyaml                    3.13                     pypi_0    pypi
pyzmq                     18.0.1           py36hc4ba49a_1    conda-forge
qt                        5.9.7                h52cfd70_1    conda-forge
qtconsole                 4.4.4                      py_0    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.22.0                   py36_0    conda-forge
rsa                       3.4.2                    pypi_0    pypi
ruamel_yaml               0.15.71         py36h14c3975_1000    conda-forge
s3transfer                0.2.0                    pypi_0    pypi
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.0.1                   py36_0    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
sip                       4.19.8          py36hf484d3e_1000    conda-forge
six                       1.12.0                py36_1000    conda-forge
snowballstemmer           1.2.1                    pypi_0    pypi
sphinx                    2.0.1                    pypi_0    pypi
sphinxcontrib-applehelp   1.0.1                    pypi_0    pypi
sphinxcontrib-devhelp     1.0.1                    pypi_0    pypi
sphinxcontrib-htmlhelp    1.0.2                    pypi_0    pypi
sphinxcontrib-jsmath      1.0.1                    pypi_0    pypi
sphinxcontrib-qthelp      1.0.2                    pypi_0    pypi
sphinxcontrib-serializinghtml 1.1.3                    pypi_0    pypi
sqlite                    3.28.0               h8b20d00_0    conda-forge
src                       0.1.0                     dev_0    <develop>
terminado                 0.8.2                    py36_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.9             h84994c4_1001    conda-forge
tornado                   6.0.2            py36h516909a_0    conda-forge
tqdm                      4.31.1                   pypi_0    pypi
traitlets                 4.3.2                 py36_1000    conda-forge
typed-ast                 1.3.5            py36h516909a_0    conda-forge
urllib3                   1.24.3                   py36_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.4                   py36_0    conda-forge
whichcraft                0.5.2                      py_1    conda-forge
widgetsnbextension        3.4.2                 py36_1000    conda-forge
wrapt                     1.11.1           py36h516909a_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
yapf                      0.27.0                     py_0    conda-forge
zeromq                    4.3.1             hf484d3e_1000    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```  
</p></details>

<p><details><summary>The conda environment of the notebook</summary>

```
$ conda list --name 4pillars_cmi_outcomes_iigrant
# packages in environment at /usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant:
#
# Name                    Version                   Build  Channel
alabaster                 0.7.12                     py_0    conda-forge
asn1crypto                0.24.0                py37_1003    conda-forge
attrs                     19.1.0                     py_0    conda-forge
awscli                    1.16.166                 py37_0    conda-forge
babel                     2.7.0                      py_0    conda-forge
backcall                  0.1.0                      py_0    conda-forge
bleach                    3.1.0                      py_0    conda-forge
botocore                  1.12.156                   py_0    conda-forge
bzip2                     1.0.6             h14c3975_1002    conda-forge
ca-certificates           2019.3.9             hecc5488_0    conda-forge
certifi                   2019.3.9                 py37_0    conda-forge
cffi                      1.12.3           py37h8022711_0    conda-forge
chardet                   3.0.4                 py37_1003    conda-forge
click                     7.0                        py_0    conda-forge
colorama                  0.3.9                      py_1    conda-forge
conda                     4.6.14                   py37_0    conda-forge
coverage                  4.5.3            py37h14c3975_0    conda-forge
cryptography              2.6.1            py37h72c5cf5_0    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cython                    0.29.7                   pypi_0    pypi
dbus                      1.13.6               he372182_0    conda-forge
decorator                 4.4.0                      py_0    conda-forge
defusedxml                0.5.0                      py_1    conda-forge
docutils                  0.14                  py37_1001    conda-forge
entrypoints               0.3                   py37_1000    conda-forge
et_xmlfile                1.0.1                    py37_0  
expat                     2.2.5             hf484d3e_1002    conda-forge
flake8                    3.7.7                    py37_0    conda-forge
fontconfig                2.13.1            he4413a7_1000    conda-forge
freetype                  2.10.0               he983fc9_0    conda-forge
gettext                   0.19.8.1          hc5be6a0_1002    conda-forge
glib                      2.58.3            hf63aee3_1001    conda-forge
gst-plugins-base          1.14.4            hdf3bae2_1001    conda-forge
gstreamer                 1.14.4            h66beb1c_1001    conda-forge
icu                       58.2              hf484d3e_1000    conda-forge
idna                      2.8                   py37_1000    conda-forge
imagesize                 1.1.0                      py_0    conda-forge
ipykernel                 5.1.1            py37h24bf2e0_0    conda-forge
ipython                   7.5.0            py37h24bf2e0_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.2                      py_0    conda-forge
jdcal                     1.4.1                      py_0    conda-forge
jedi                      0.13.3                   py37_0    conda-forge
jinja2                    2.10.1                     py_0    conda-forge
jmespath                  0.9.4                      py_0    conda-forge
jpeg                      9c                h14c3975_1001    conda-forge
jsonschema                3.0.1                    py37_0    conda-forge
jupyter_client            5.2.4                      py_3    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.1.0            py37hc9558a2_0    conda-forge
libblas                   3.8.0               10_openblas    conda-forge
libcblas                  3.8.0               10_openblas    conda-forge
libffi                    3.2.1             he1b5a44_1006    conda-forge
libgcc-ng                 8.2.0                hdf63c60_1  
libgfortran-ng            7.3.0                hdf63c60_0  
libiconv                  1.15              h516909a_1005    conda-forge
liblapack                 3.8.0               10_openblas    conda-forge
libpng                    1.6.37               hed695b0_0    conda-forge
libsodium                 1.0.16            h14c3975_1001    conda-forge
libstdcxx-ng              8.2.0                hdf63c60_1  
libuuid                   2.32.1            h14c3975_1000    conda-forge
libxcb                    1.13              h14c3975_1002    conda-forge
libxml2                   2.9.9                h13577e0_0    conda-forge
markupsafe                1.1.1            py37h14c3975_0    conda-forge
matplotlib                3.1.0                    py37_1    conda-forge
matplotlib-base           3.1.0            py37hfd891ef_1    conda-forge
mccabe                    0.6.1                      py_1    conda-forge
mistune                   0.8.4           py37h14c3975_1000    conda-forge
nb_conda_kernels          2.2.2                    py37_0    conda-forge
nbconvert                 5.5.0                      py_0    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
ncurses                   6.1               hf484d3e_1002    conda-forge
nodejs                    11.14.0              he1b5a44_1    conda-forge
notebook                  5.7.8                    py37_0    conda-forge
numpy                     1.16.3           py37he5ce36f_0    conda-forge
openblas                  0.3.6                h6e990d7_2    conda-forge
openpyxl                  2.6.1                      py_0    conda-forge
openssl                   1.1.1b               h14c3975_1    conda-forge
packaging                 19.0                       py_0    conda-forge
pandas                    0.24.2           py37hb3f55d8_0    conda-forge
pandoc                    2.7.2                         0    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
parso                     0.4.0                      py_0    conda-forge
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.41              hf484d3e_1003    conda-forge
pexpect                   4.7.0                    py37_0    conda-forge
pickleshare               0.7.5                 py37_1000    conda-forge
pip                       19.1                     py37_0    conda-forge
prometheus_client         0.6.0                      py_0    conda-forge
prompt_toolkit            2.0.9                      py_0    conda-forge
pthread-stubs             0.4               h14c3975_1001    conda-forge
ptyprocess                0.6.0                   py_1001    conda-forge
pyasn1                    0.4.5                      py_0    conda-forge
pycap                     0.0.0                    pypi_0    pypi
pycodestyle               2.5.0                      py_0    conda-forge
pycosat                   0.6.3           py37h14c3975_1001    conda-forge
pycparser                 2.19                     py37_1    conda-forge
pyflakes                  2.1.1                      py_0    conda-forge
pygments                  2.4.2                      py_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
pyparsing                 2.4.0                      py_0    conda-forge
pyqt                      5.9.2            py37hcca6a23_0    conda-forge
pyrsistent                0.15.2           py37h516909a_0    conda-forge
pysocks                   1.7.0                    py37_0    conda-forge
python                    3.7.3                h5b0a415_0    conda-forge
python-dateutil           2.8.0                      py_0    conda-forge
python-dotenv             0.10.2                     py_0    conda-forge
pytz                      2019.1                     py_0    conda-forge
pyyaml                    3.13            py37h14c3975_1001    conda-forge
pyzmq                     18.0.1           py37hc4ba49a_1    conda-forge
qt                        5.9.7                h52cfd70_2    conda-forge
readline                  7.0               hf8c457e_1001    conda-forge
requests                  2.22.0                   py37_0    conda-forge
rsa                       3.4.2                      py_1    conda-forge
ruamel_yaml               0.15.71         py37h14c3975_1000    conda-forge
s3transfer                0.2.0                    py37_0    conda-forge
scipy                     1.3.0            py37hab63836_0    conda-forge
semantic-version          2.3.1                    pypi_0    pypi
send2trash                1.5.0                      py_0    conda-forge
setuptools                41.0.1                   py37_0    conda-forge
sip                       4.19.8          py37hf484d3e_1000    conda-forge
six                       1.12.0                py37_1000    conda-forge
snowballstemmer           1.2.1                      py_1    conda-forge
sphinx                    2.0.1                      py_0    conda-forge
sphinxcontrib-applehelp   1.0.1                      py_0    conda-forge
sphinxcontrib-devhelp     1.0.1                      py_0    conda-forge
sphinxcontrib-htmlhelp    1.0.2                      py_0    conda-forge
sphinxcontrib-jsmath      1.0.1                      py_0    conda-forge
sphinxcontrib-qthelp      1.0.2                      py_0    conda-forge
sphinxcontrib-serializinghtml 1.1.1                      py_0    conda-forge
sqlite                    3.28.0               h8b20d00_0    conda-forge
src                       0.1.0                     dev_0    <develop>
statsmodels               0.9.0           py37h3010b51_1000    conda-forge
terminado                 0.8.2                    py37_0    conda-forge
testpath                  0.4.2                   py_1001    conda-forge
tk                        8.6.9             h84994c4_1001    conda-forge
tornado                   6.0.2            py37h516909a_0    conda-forge
traitlets                 4.3.2                 py37_1000    conda-forge
urllib3                   1.24.3                   py37_0    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                      py_1    conda-forge
wheel                     0.33.4                   py37_0    conda-forge
widgetsnbextension        3.4.2                 py37_1000    conda-forge
xlrd                      1.2.0                      py_0    conda-forge
xorg-libxau               1.0.9                h14c3975_0    conda-forge
xorg-libxdmcp             1.1.3                h516909a_0    conda-forge
xz                        5.2.4             h14c3975_1001    conda-forge
yaml                      0.1.7             h14c3975_1001    conda-forge
zeromq                    4.3.1             hf484d3e_1000    conda-forge
zlib                      1.2.11            h14c3975_1004    conda-forge
```

</details>
Given I am using a notebook in a conda environment with an installed kernel, when I execute:

```
jupyter nbconvert --to html --execute notebooks/Explore.ipynb
```
<p><details><summary>I get the results...</summary>

```
[NbConvertApp] Converting notebook notebooks/Explore.ipynb to html
Traceback (most recent call last):
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/bin/jupyter-nbconvert", line 10, in <module>
    sys.exit(main())
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/jupyter_core/application.py", line 266, in launch_instance
    return super(JupyterApp, cls).launch_instance(argv=argv, **kwargs)
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 338, in start
    self.convert_notebooks()
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 508, in convert_notebooks
    self.convert_single_notebook(notebook_filename)
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 479, in convert_single_notebook
    output, resources = self.export_single_notebook(notebook_filename, resources, input_buffer=input_buffer)
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/nbconvert/nbconvertapp.py", line 408, in export_single_notebook
    output, resources = self.exporter.from_filename(notebook_filename, resources=resources)
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 179, in from_filename
    return self.from_file(f, resources=resources, **kw)
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 197, in from_file
    return self.from_notebook_node(nbformat.read(file_stream, as_version=4), resources=resources, **kw)
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/nbconvert/exporters/html.py", line 90, in from_notebook_node
    return super(HTMLExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/nbconvert/exporters/templateexporter.py", line 299, in from_notebook_node
    nb_copy, resources = super(TemplateExporter, self).from_notebook_node(nb, resources, **kw)
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 139, in from_notebook_node
    nb_copy, resources = self._preprocess(nb_copy, resources)
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/nbconvert/exporters/exporter.py", line 316, in _preprocess
    nbc, resc = preprocessor(nbc, resc)
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/nbconvert/preprocessors/base.py", line 47, in __call__
    return self.preprocess(nb, resources)
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 379, in preprocess
    with self.setup_preprocessor(nb, resources, km=km):
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 324, in setup_preprocessor
    self.km, self.kc = self.start_new_kernel(cwd=path)
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/nbconvert/preprocessors/execute.py", line 271, in start_new_kernel
    km.start_kernel(extra_arguments=self.extra_arguments, **kwargs)
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/jupyter_client/manager.py", line 246, in start_kernel
    kernel_cmd = self.format_kernel_cmd(extra_arguments=extra_arguments)
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/jupyter_client/manager.py", line 170, in format_kernel_cmd
    cmd = self.kernel_spec.argv + extra_arguments
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/jupyter_client/manager.py", line 82, in kernel_spec
    self._kernel_spec = self.kernel_spec_manager.get_kernel_spec(self.kernel_name)
  File "/usr/share/miniconda3/envs/4pillars_cmi_outcomes_iigrant/lib/python3.7/site-packages/jupyter_client/kernelspec.py", line 236, in get_kernel_spec
    raise NoSuchKernel(kernel_name)
jupyter_client.kernelspec.NoSuchKernel: No such kernel named conda-env-4pillars_cmi_outcomes_iigrant-py
```  
</p></details>

When I execute:

```
jupyter nbconvert --to html --ExecutePreprocessor.kernel_name=python3 notebooks/Explore.ipynb
```
or
```
jupyter nbconvert --to html --ExecutePreprocessor.kernel_name=4pillars_cmi_outcomes_iigrant notebooks/Explore.ipynb
```
The file is generated, but without the output.

The goal is to implement a process that strips output for version control, but still allows me to generate versions with output that I can share with others. I have yet to find a solution that don't involve hacking something (and then trying to teach others how to do the same ugly hacks on their systems).

* `nbstripout` would work, except the path to the module is hardcoded in `<project>/.git/.gitconfig` which breaks the filter for other users. A global `.gitconfig` would be nice, but is not supported out-of-the-box.

* pre-save hooks in `jupyter_notebook_config.py` work great, except this issue prevents me from exporting versions with the output.

* `nbdime` seems to help the diff/merge problem but does not strip output.

Any suggestions would be appreciated.

**Comment by mcg1969** [comment]
There really is not, I'm afraid. #104 is a step in this direction, sure, but it hasn't proven sufficiently foolproof. It's important to understand that the _notebook_ package has hooks that the larger Jupyter project just doesn't, yet.

That said, I do believe the next major revision of Jupyter is going to expose a flexible kernel discovery mechanism for all applications that need it, including nbconvert. That is, frankly, what is needed here.

**Comment by fcollonval** [comment]
@mcg1969 I think this can now be close as there is a way to render environment visible by nbconvert through `kernelspec_path` configuration parameter.
